name: Format and Lint Check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  format-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build the image with cache
        uses: docker/build-push-action@v4
        with:
          load: true
          context: .
          file: Dockerfile
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Run go format and lint check
        run: |
          FMT_OUTPUT=$(docker compose run --rm app go fmt ./...)
          if [ -n "$FMT_OUTPUT" ]; then
            echo "$FMT_OUTPUT"
            echo "Go formatting required. Please run 'go fmt ./...'."
            exit 1
          fi

      - name: Run front format and lint check
        run: |
          docker compose run --rm front make check/front/ci

      - name: Cleanup
        if: always()
        run: docker compose down
