name: Format and Lint Check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  format-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@c47758b77c9736f4b2ef4073d4d51994fabfe349 # v3

      - name: Build the image with cache
        uses: docker/build-push-action@48aba3b46d1b1fec4febb7c5d0c644b249a11355 # v6
        with:
          load: true
          context: .
          file: Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run go format and lint check
        run: |
          docker compose run --rm app sh -c "
          FMT_OUTPUT=\$(go fmt ./...)
          if [ -n \"\$FMT_OUTPUT\" ]; then
            echo \"\$FMT_OUTPUT\"
            echo \"Go formatting required. Please run 'go fmt ./...'.\"
            exit 1
          fi
          "

      - name: Run front format and lint check
        run: |
          docker compose run --rm front sh -c '
          npm install
          npm run typecheck
          npx @biomejs/biome ci
          '

      - name: Cleanup
        if: always()
        run: docker compose down
