name: Format and Lint Check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  format-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@6524bf65af31da8d45b59e8c27de4bd072b392f5 # v3

      - name: Build with docker compose + BuildKit cache
        run: |
          docker buildx create --use || true
          docker compose build \
            --progress=plain \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            --cache-from=type=gha \
            --cache-to=type=gha,mode=max

      - name: Run go format and lint check
        run: |
          docker compose run --rm app sh -c "
          FMT_OUTPUT=\$(go fmt ./...)
          if [ -n \"\$FMT_OUTPUT\" ]; then
            echo \"\$FMT_OUTPUT\"
            echo \"Go formatting required. Please run 'go fmt ./...'.\"
            exit 1
          fi
          "

      - name: Run front format and lint check
        run: |
          docker compose run --rm --entrypoint "" front-test sh -c '
          npm ci
          npm run typecheck
          npx @biomejs/biome ci
          '

      - name: Cleanup
        if: always()
        run: docker compose down
