name: Run Tests with Docker Compose

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@6524bf65af31da8d45b59e8c27de4bd072b392f5 # v3

      - name: Build with docker compose + BuildKit cache
        run: |
          docker buildx create --use || true
          docker compose build \
            --progress=plain \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            --cache-from=type=gha \
            --cache-to=type=gha,mode=max

      - name: Run front tests
        run: |
          docker compose run --rm --entrypoint "" front-test sh -c '
          npm ci
          npm run test/ci
          '

      - name: Shutdown services
        if: always()
        run: docker compose down
