name: Run Tests with Docker Compose

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@c47758b77c9736f4b2ef4073d4d51994fabfe349 # v3

      - name: Build the image with cache
        uses: docker/build-push-action@0a97817b6ade9f46837855d676c4cca3a2471fc9 # v4
        with:
          load: true
          context: .
          file: Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run front tests
        run: |
          docker compose run --rm --entrypoint "" front-test sh -c '
          npm install
          npm run test/ci
          '

      - name: Shutdown services
        if: always()
        run: docker compose down
